/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/future-is-our-legacy-18babb7cc04146ada3e3f80c4739d91a
title: Future is our legacy
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("Evee.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.82}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1.3, 0]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.GOLD}
            />
          </group>
          <group position={[0, -0.82, 0]}>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials["Material.005"]}
          />
          <group position={[0, -1.02, 0]}>
            <mesh
              geometry={nodes.Object_17.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials.GOLD}
            />
          </group>
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials["Material.004"]}
          />
          <group rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials["Material.010"]}
          />
          <group position={[0, -0.82, 0]}>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials["Material.009"]}
            />
          </group>
          <mesh geometry={nodes.Object_32.geometry} material={materials.GOLD} />
          <group position={[0, -0.82, 0]}>
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials["Material.005"]}
          />
          <mesh geometry={nodes.Object_37.geometry} material={materials.GOLD} />
          <mesh
            geometry={nodes.Object_39.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Object_40.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials["Material.001"]}
          />
          <mesh geometry={nodes.Object_43.geometry} material={materials.GOLD} />
          <mesh
            geometry={nodes.Object_45.geometry}
            material={materials["Material.004"]}
          />
          <group position={[0, 4.28, 0]}>
            <mesh
              geometry={nodes.Object_47.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <group position={[0, 4.28, 0]}>
            <mesh
              geometry={nodes.Object_49.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_51.geometry}
            material={materials["Material.004"]}
          />
          <group
            position={[0, 17.06, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.22}
          >
            <mesh
              geometry={nodes.Object_53.geometry}
              material={materials.GOLD}
            />
          </group>
          <mesh
            geometry={nodes.Object_55.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            geometry={nodes.Object_56.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            geometry={nodes.Object_57.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Object_58.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            geometry={nodes.Object_59.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Object_61.geometry}
            material={materials["Material.001"]}
          />
          <mesh geometry={nodes.Object_62.geometry} material={materials.GOLD} />
          <mesh
            geometry={nodes.Object_63.geometry}
            material={materials["Material.006"]}
          />
          <group position={[0, 0.01, 0]}>
            <mesh
              geometry={nodes.Object_65.geometry}
              material={materials.GOLD}
            />
            <mesh
              geometry={nodes.Object_66.geometry}
              material={materials["Material.036"]}
            />
            <mesh
              geometry={nodes.Object_67.geometry}
              material={materials["Material.037"]}
            />
            <mesh
              geometry={nodes.Object_68.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_69.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_70.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_71.geometry}
              material={materials["Material.031"]}
            />
            <mesh
              geometry={nodes.Object_72.geometry}
              material={materials["Material.034"]}
            />
            <mesh
              geometry={nodes.Object_73.geometry}
              material={materials["Material.035"]}
            />
            <mesh
              geometry={nodes.Object_74.geometry}
              material={materials["Material.033"]}
            />
            <mesh
              geometry={nodes.Object_75.geometry}
              material={materials["Material.032"]}
            />
          </group>
          <group
            position={[0, 0, 0]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.03}
          >
            <group position={[-8.44, 8.47, -0.48]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_79.geometry}
                  material={materials.GOLD}
                />
              </group>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_81.geometry}
                  material={materials.Blanc}
                />
              </group>
              <group position={[56.22, -0.6, -37.6]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_83.geometry}
                  material={materials.Blanc}
                />
                <mesh
                  geometry={nodes.Object_84.geometry}
                  material={materials.GOLD}
                />
              </group>
            </group>
          </group>
          <group position={[0, 2.84, 0]}>
            <mesh
              geometry={nodes.Object_86.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[0, 0.97, 0]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.03}
          >
            <group position={[-8.44, 8.47, -0.48]}>
              <group position={[7.71, -0.6, -1.11]} scale={4.81}>
                <mesh
                  geometry={nodes.Object_90.geometry}
                  material={materials.Material}
                />
                <mesh
                  geometry={nodes.Object_91.geometry}
                  material={materials["Material.015"]}
                />
              </group>
            </group>
          </group>
          <mesh
            geometry={nodes.Object_93.geometry}
            material={materials["Material.005"]}
          />
          <group position={[0.46, -65.16, 0.34]} scale={0.28}>
            <mesh
              geometry={nodes.Object_95.geometry}
              material={materials.GOLD}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_97.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              geometry={nodes.Object_98.geometry}
              material={materials.GOLD}
            />
          </group>
          <mesh
            geometry={nodes.Object_100.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Object_101.geometry}
            material={materials.GOLD}
          />
          <group position={[0, 0.01, 2.29]} scale={0.94}>
            <mesh
              geometry={nodes.Object_103.geometry}
              material={materials.GOLD}
            />
            <mesh
              geometry={nodes.Object_104.geometry}
              material={materials["Material.036"]}
            />
            <mesh
              geometry={nodes.Object_105.geometry}
              material={materials["Material.037"]}
            />
            <mesh
              geometry={nodes.Object_106.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_107.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_108.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_109.geometry}
              material={materials["Material.031"]}
            />
            <mesh
              geometry={nodes.Object_110.geometry}
              material={materials["Material.034"]}
            />
            <mesh
              geometry={nodes.Object_111.geometry}
              material={materials["Material.035"]}
            />
            <mesh
              geometry={nodes.Object_112.geometry}
              material={materials["Material.033"]}
            />
            <mesh
              geometry={nodes.Object_113.geometry}
              material={materials["Material.032"]}
            />
          </group>
          <group
            position={[-0.04, -0.42, -1.04]}
            rotation={[-3.14, 0, 0]}
            scale={0.26}
          >
            <mesh
              geometry={nodes.Object_115.geometry}
              material={materials["Carosserie.001"]}
            />
            <mesh
              geometry={nodes.Object_116.geometry}
              material={materials["Material.023"]}
            />
            <mesh
              geometry={nodes.Object_117.geometry}
              material={materials["Blanck.001"]}
            />
            <mesh
              geometry={nodes.Object_118.geometry}
              material={materials.CARBONE}
            />
            <mesh
              geometry={nodes.Object_119.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Object_120.geometry}
              material={materials.Jantes}
            />
            <mesh
              geometry={nodes.Object_121.geometry}
              material={materials["Rouge.001"]}
            />
            <mesh
              geometry={nodes.Object_122.geometry}
              material={materials.material_31}
            />
            <mesh
              geometry={nodes.Object_123.geometry}
              material={materials["Orange.001"]}
            />
            <mesh
              geometry={nodes.Object_124.geometry}
              material={materials["Sige.001"]}
            />
            <mesh
              geometry={nodes.Object_125.geometry}
              material={materials["Vert.001"]}
            />
            <mesh
              geometry={nodes.Object_126.geometry}
              material={materials["Blanc.001"]}
            />
            <mesh
              geometry={nodes.Object_127.geometry}
              material={materials["Material.039"]}
            />
            <mesh
              geometry={nodes.Object_128.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              geometry={nodes.Object_129.geometry}
              material={materials["Material.027"]}
            />
            <mesh
              geometry={nodes.Object_130.geometry}
              material={materials["Material.042"]}
            />
            <mesh
              geometry={nodes.Object_131.geometry}
              material={materials["Material.040"]}
            />
            <mesh
              geometry={nodes.Object_132.geometry}
              material={materials.Lumire_rouge}
            />
            <mesh
              geometry={nodes.Object_133.geometry}
              material={materials["Material.029"]}
            />
            <mesh
              geometry={nodes.Object_134.geometry}
              material={materials.material_43}
            />
            <mesh
              geometry={nodes.Object_135.geometry}
              material={materials.Vitres}
            />
            <mesh
              geometry={nodes.Object_136.geometry}
              material={materials.Lumire_blanche}
            />
            <mesh
              geometry={nodes.Object_137.geometry}
              material={materials.Tire}
            />
            <mesh
              geometry={nodes.Object_138.geometry}
              material={materials.Volant}
            />
            <mesh
              geometry={nodes.Object_139.geometry}
              material={materials.Jantes_I}
            />
            <mesh
              geometry={nodes.Object_140.geometry}
              material={materials["Material.041"]}
            />
            <mesh
              geometry={nodes.Object_141.geometry}
              material={materials.Lumire_Orange}
            />
          </group>
          <group scale={13.78}>
            <mesh
              geometry={nodes.Object_143.geometry}
              material={materials["Material.043"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("Evee.gltf");
